app/owners/models.py
from app import db
from datetime import datetime

owners_and_pets = db.Table('owners_pets',
                           db.Column('pets_id', db.Integer, db.ForeignKey('pets_model.id', ondelete='CASCADE'), primary_key=True),
                           db.Column('owner_id', db.Integer, db.ForeignKey('owner_model.id', ondelete='CASCADE'), primary_key=True)
                           )


class OwnerModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    city = db.Column(db.String(30), nullable=False)
    date = db.Column(db.DateTime, default=datetime.now())
    work = db.Column(db.Integer)
    pets = db.relationship('PetsModel', secondary=owners_and_pets, lazy=True,
                           backref=db.backref('owners', lazy=True))


class PetsModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    type_pet = db.Column(db.String(30), nullable=False)
    date = db.Column(db.DateTime, default=datetime.now())
    # ownerID = db.Column(db.Integer, db.ForeignKey('owner_model.id', ondelete='CASCADE'), nullable=False)

app/owners/forms.py
from wtforms import Form, StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired, length, NumberRange


class Owener(Form):
    name_own = StringField('Name_Own', [DataRequired(), length(2, 30, 'name 2-30 symbols')])
    age_own = IntegerField('Age_Own', [DataRequired('must be number'), NumberRange(5, 120, 'age must be 1-120')])
    city_owm = StringField('City_Own', [DataRequired(), length(3, 20, 'name 3-20 symbols')])
    save = SubmitField('Save')


class Add_Pet(Form):
    name_pet = StringField('Name_Pet', [DataRequired(), length(2, 20, 'name 2-30 symbols')])
    age_pet = IntegerField('Age_Pet', [DataRequired('must be number'), NumberRange(1, 50, 'age must be 1-50')])
    type_pet = StringField('Type_Pet', [DataRequired(), length(2, 15, 'type 2-15 symbols')])
    save = SubmitField('Save')

app/owners/views.py
from flask import Blueprint, render_template, request, redirect, url_for

from app.owners.forms import Owener, Add_Pet
from app import db

owners = Blueprint('owners', __name__, template_folder='templates', static_folder='static')

from .models import OwnerModel, PetsModel


@owners.route('/', methods=['POST', 'GET'])
def owners_page():
    form = Owener(request.form)

    if request.method == 'POST' and form.validate():
        name = request.form['name_own']
        age = request.form['age_own']
        city = request.form['city_owm']
        owner = OwnerModel(name=name, age=age, city=city)
        db.session.add(owner)
        db.session.commit()
        return redirect(url_for('owners.owners_page'))

    ownersMod = OwnerModel.query.all()
    print(owners)
    return render_template('owners/owners_page.html', owners=ownersMod, form=form)


@owners.route('/<userID>', methods=['POST', 'GET'])
def user_page(userID):
    user = OwnerModel.query.get(userID)

    return render_template('owners/user_page.html', user=user)


@owners.route('/<ownerID>/add_pet', methods=['POST', 'GET'])
def add_pet_page(ownerID):
    form = Add_Pet(request.form)
    user = OwnerModel.query.get(ownerID)
    # pets = PetsModel.query.filter_by(ownerID=ownerID)

    if request.method == 'POST' and form.validate():
        name_pet = request.form['name_pet']
        age_pet = request.form['age_pet']
        type_pet = request.form['type_pet']

        pet = PetsModel(name=name_pet, age=age_pet, type_pet=type_pet)
        user.pets.append(pet)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('owners.add_pet_page', ownerID=ownerID))
    return render_template('owners/add_pet_page.html', form=form, user=user)


@owners.route('/delete_owner/<int:id>')
def delete_owner(id):
    OwnerModel.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for('owners.owners_page'))


@owners.route('/delete_pet/<int:id_pet>/<int:owner_id>')
def delete_pet(id_pet, owner_id):
    PetsModel.query.filter_by(id=id_pet).delete()
    db.session.commit()
    return redirect(url_for('owners.add_pet_page', ownerID=owner_id))

app/owners/templates/owners/add_pet_page.html
{% extends 'base.html' %}

{% block title %}
    add pet page
{% endblock %}

{% block body %}
    <h1>ADD PET</h1>
    <div>Add page by {{ user.name }}</div>

    <h1></h1>


    <form method="POST">
        {% for input in form %}
            <div>
                {% if  input != form.save %}
                    {{ input.label }}
                {% endif %}
                {{ input }}
            </div>
        {% endfor %}
    </form>

    {% for pet in user.pets %}
        <div>
            <br>
            <div>pet id -  {{ pet.id }}</div>
            <div> pet name - {{ pet.name }}</div>
            <div>pet age - {{ pet.age }}</div>
            <div>pet type - {{ pet.type_pet }}</div>
            <div>date of create - {{ pet.date }}</div>

            <a href="{{ url_for('owners.delete_pet', id_pet = pet.id, owner_id = user.id) }}">
                <button>delete {{ pet.name }}</button>
            </a>
            <br>
        </div>
    {% endfor %}



{% endblock %}

app/owners/templates/owners/owners_page.html
{% extends 'base.html' %}

{% block title %}
    Owners | Page
{% endblock %}

{% block body %}

    <h1>OWNERS PAGE</h1>
    <br>
    <h2>Add Owner</h2>
    <form action="{{ url_for('owners.owners_page') }}" method="POST">
        {% for foo in form %}

            {% if  foo != form.save %}
                {{ foo.label }}
            {% endif %}

            {% if foo != form.city_owm and foo != form.save %}
                <span style="color: red"> * </span>
            {% endif %}

            {{ foo }}

            {% if foo.errors %}
                {{ foo.errors[0] }}
            {% endif %}
        {% endfor %}

    </form>
    <br>
    <h2>Owners List:</h2>

    {% for owner in owners %}
        <div>
            <div>Owner ID - {{ owner['id'] }}</div>
            <div><a href={{ url_for('owners.user_page',userID = owner['id'] ) }}> name: {{ owner['name'] }}</a></div>
            <div>age: {{ owner['age'] }}</div>
            <div>city: {{ owner['city'] }}</div>

            <div><button class="btn" style="background: red">
                <a href="{{ url_for('owners.delete_owner', id = owner['id']) }}">X</a>
            </button></div>
        </div>
        <br>
    {% endfor %}
{% endblock %}

app/owners/templates/owners/user_page.html
{% extends 'base.html' %}
{% block title %}
    user page
{% endblock %}

{% block body %}
    <h1>This is user Page</h1>
    <br>
    <div><h2>User ID - {{ user.id }}</h2></div>
    <div><h2>Name - {{ user.name }}</h2></div>
    <div><h2>Age - {{ user.age }}</h2></div>
    <div><h2>City - {{ user.city }}</h2></div>
    <div><h2>Date of create - {{ user.date }}</h2></div>
    <br>
    <h3>User pets:</h3>
    <button class="btn" style="background: #3A7734">
        <a href="{{ url_for('owners.add_pet_page', ownerID = user.id) }}">
            Create new pet
        </a>
    </button>

    <div>

    {% for pet in user.pets %}
            <div>{{ pet.name }}</div>
        {% endfor %}
    </div>
{% endblock %}