app/owners/models.py
from app import db
from datetime import datetime

owners_and_pets = db.Table('owners_pets',
                           db.Column('pets_id', db.Integer, db.ForeignKey('pets_model.id', ondelete='CASCADE'), primary_key=True),
                           db.Column('owner_id', db.Integer, db.ForeignKey('owner_model.id', ondelete='CASCADE'), primary_key=True)
                           )


class OwnerModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    city = db.Column(db.String(30), nullable=False)
    date = db.Column(db.DateTime, default=datetime.now())
    work = db.Column(db.Integer)
    pets = db.relationship('PetsModel', secondary=owners_and_pets, lazy=True,
                           backref=db.backref('owners', lazy=True))


class PetsModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    type_pet = db.Column(db.String(30), nullable=False)
    date = db.Column(db.DateTime, default=datetime.now())
    # ownerID = db.Column(db.Integer, db.ForeignKey('owner_model.id', ondelete='CASCADE'), nullable=False)

app/owners/forms.py
from wtforms import Form, StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired, length, NumberRange


class Owener(Form):
    name_own = StringField('Name_Own', [DataRequired(), length(2, 30, 'name 2-30 symbols')])
    age_own = IntegerField('Age_Own', [DataRequired('must be number'), NumberRange(5, 120, 'age must be 1-120')])
    city_owm = StringField('City_Own', [DataRequired(), length(3, 20, 'name 3-20 symbols')])
    save = SubmitField('Save')


class Add_Pet(Form):
    name_pet = StringField('Name_Pet', [DataRequired(), length(2, 20, 'name 2-30 symbols')])
    age_pet = IntegerField('Age_Pet', [DataRequired('must be number'), NumberRange(1, 50, 'age must be 1-50')])
    type_pet = StringField('Type_Pet', [DataRequired(), length(2, 15, 'type 2-15 symbols')])
    save = SubmitField('Save')

app/posts/forms.py
from wtforms import Form, StringField, SubmitField


class Posts_Form(Form):
    naaame = StringField('Name') # {"naaame": "Value"}
    mail = StringField('Mail')
    send = SubmitField()

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import DevConfig

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

app = Flask(__name__)
app.config.from_object(DevConfig)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

from .posts.views import posts
from .owners.views import owners

app.register_blueprint(posts, url_prefix='/posts')
app.register_blueprint(owners, url_prefix='/owners')

from app import views

app/owners/views.py
from flask import Blueprint, render_template, request, redirect, url_for

from app.owners.forms import Owener, Add_Pet
from app import db

owners = Blueprint('owners', __name__, template_folder='templates', static_folder='static')

from .models import OwnerModel, PetsModel


@owners.route('/', methods=['POST', 'GET'])
def owners_page():
    form = Owener(request.form)

    if request.method == 'POST' and form.validate():
        name = request.form['name_own']
        age = request.form['age_own']
        city = request.form['city_owm']
        owner = OwnerModel(name=name, age=age, city=city)
        db.session.add(owner)
        db.session.commit()
        return redirect(url_for('owners.owners_page'))

    ownersMod = OwnerModel.query.all()
    print(owners)
    return render_template('owners/owners_page.html', owners=ownersMod, form=form)


@owners.route('/<userID>', methods=['POST', 'GET'])
def user_page(userID):
    user = OwnerModel.query.get(userID)

    return render_template('owners/user_page.html', user=user)


@owners.route('/<ownerID>/add_pet', methods=['POST', 'GET'])
def add_pet_page(ownerID):
    form = Add_Pet(request.form)
    user = OwnerModel.query.get(ownerID)
    # pets = PetsModel.query.filter_by(ownerID=ownerID)

    if request.method == 'POST' and form.validate():
        name_pet = request.form['name_pet']
        age_pet = request.form['age_pet']
        type_pet = request.form['type_pet']

        pet = PetsModel(name=name_pet, age=age_pet, type_pet=type_pet)
        user.pets.append(pet)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('owners.add_pet_page', ownerID=ownerID))
    return render_template('owners/add_pet_page.html', form=form, user=user)


@owners.route('/delete_owner/<int:id>')
def delete_owner(id):
    OwnerModel.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for('owners.owners_page'))


@owners.route('/delete_pet/<int:id_pet>/<int:owner_id>')
def delete_pet(id_pet, owner_id):
    PetsModel.query.filter_by(id=id_pet).delete()
    db.session.commit()
    return redirect(url_for('owners.add_pet_page', ownerID=owner_id))

app/posts/views.py
from flask import Blueprint, render_template, request

from app.posts.forms import Posts_Form

posts = Blueprint('posts', __name__, template_folder='templates', static_folder='static')


@posts.route('/')
def indexx():
    return render_template('posts/indexx.html')


@posts.route('/new/', methods=['POST', 'GET'])
def new_page():
    form = Posts_Form()
    name = ''
    mail = ''
    if request.method == 'POST':
        print(f'this is req {dict(request.form)}')
        name = request.form['naaame']
        mail = request.form['mail']
    return render_template('posts/new_post.html', name=name, mail=mail, form=form)

app/views.py
from flask import render_template, request
from app import app


@app.route('/')
def home_page():
    return render_template('index.html')


@app.route('/about')
def about_page():
    return render_template('about.html')


@app.route('/search/')
def search_page():
    result = request.args['search']
    return render_template('search.html', search=result)

app/templates/about.html
{% extends 'base.html' %}
{% block title %}
    about page
{% endblock %}

{% block body %}
    <div>
        <h1>ABOUT PAGE</h1>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href={{ url_for('static', filename = 'css/style.css') }}>
    {% block css_js_links %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href={{ url_for('home_page') }}>Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={{ url_for('about_page') }}>About Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.new_page') }}">New Page</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('owners.owners_page') }}">Owners</a>
                    </li>



                </ul>
                <form class=" form-inline my-2 my-lg-0" action="{{ url_for('search_page') }}">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                           name="search" value="{{ request.args.get('search', '') }}">
                    <button class=" btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>


            </div>
        </nav>
        <div>
            {% block body %}

            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
    home | page
{% endblock %}


{% block body %}
    <div>
        <h1>HOME PAGE</h1>
    </div>
{% endblock %}

app/templates/search.html
{% extends 'base.html' %}

{% block title %}
    search | page
{% endblock %}


{% block body %}
    <div>
        SEARCH PAGE
    </div>
    search = {{ search }}
{% endblock %}